config/routes.rb
Rails.application.routes.draw do

  resources :announcements, only: [:index, :edit, :update]

  get 'faqs/reorder', to: 'faqs#reorder', as: :reorder_faq
  resources :faqs do
    member do
      patch :move_up
      patch :move_down
    end
  end
  resources :reports, only: [:index] do
    collection do
      get 'information_requests_report', to: 'reports#information_requests_report'
      get 'loan_requests_report', to: 'reports#loan_requests_report'
      get 'import_data_report', to: 'reports#import_data_report'
    end
  end

  resource :profile, only: [:show, :edit, :update] do
    get :show_loan_questions
    get :edit_loan_questions          # profile_loan_questions_path
    patch :update_loan_questions # profile_update_loan_questions_path
    get "profile_info", to: "profiles#profile_info", as: :profile_info
  end
  get 'profile/collections_questions', to: 'profiles#show_collections_questions', as: 'show_collections_questions_profile'
  get 'profile/collection_questions/:id', to: 'profiles#collection_questions', as: 'collection_questions_profile'
  patch 'profile/collection_questions/:id', to: 'profiles#update_collection_questions', as: 'update_collection_questions_profile'

  resources :users, only: [:edit, :update]

  resources :addresses, only: [:show, :edit, :update, :destroy, :new, :create, :index] do
    member do
      patch :set_primary
    end
  end

  get 'app_preference/:name/:global', to: 'app_preferences#delete_preference', as: :delete_preference
  get 'app_preferences/app_prefs', to: 'app_preferences#app_prefs', as: :app_prefs
  post 'app_preferences/app_prefs', to: 'app_preferences#save_app_prefs'
  get 'app_preferences/delete_image/:pref_id', to: 'app_preferences#delete_image', as: :delete_image_app_prefs
  resources :app_preferences

  resources :information_requests, only: [:new, :show]
  post "information_requests/send_information_request", to: "information_requests#send_information_request", as: :send_information_request
  get "information_requests/show_modal/:id", to: "information_requests#show_modal", as: :information_request_show_modal

  get "loan_requests/step_two", to: "loan_requests#step_two", as: :step_two
  get "loan_requests/step_three", to: "loan_requests#step_three", as: :step_three
  get "loan_requests/step_four", to: "loan_requests#step_four", as: :step_four
  get "loan_requests/step_five", to: "loan_requests#step_five", as: :step_five
  resources :loan_requests, only: [:new, :show]
  post "loan_requests/send_loan_request", to: "loan_requests#send_loan_request", as: :send_loan_request

  post "loan_requests/enable", to: "loan_requests#enable", as: :enable_loan_request
  post "loan_questions/enable_preview", to: "loan_questions#enable_preview", as: :preview_loan_questions_access
  post "faqs/enable_preview", to: "faqs#enable_preview", as: :preview_faqs_access
  post "collections/enable_preview", to: "collections#enable_preview", as: :preview_collections_access
  post "checkout/enable_preview", to: "checkout#enable_preview", as: :preview_checkout_access
  post "home/enable_preview", to: "home#enable_preview", as: :preview_about_access


  patch "update_loan_answer/:id", to: "loan_answers#update", as: :update_loan_answer
  get "edit_loan_answer/:id", to: "loan_answers#edit", as: :edit_loan_answer

  get "profile/edit_field/:field", to: "profiles#edit_field", as: :edit_user_field
  patch "profile/update_field/:field", to: "profiles#update_field", as: :update_user_field

  get "loan_questions/preview", to: "loan_questions#preview", as: :preview_loan_questions
  resources :loan_questions do
    member do
      patch :move_up
      patch :move_down
    end
  end
  get "checkout", to: "checkout#show"
  post "checkout/add"
  post "checkout/change"
  post "checkout/remove"
  post "checkout/remove_preparation"
  post "checkout/save_for_later"
  post "checkout/move_back"
  post "checkout/remove_unavailable"
  post "checkout/remove_no_longer_available"

  get 'export_to_csv', to: 'items#export_to_csv', as: :export_to_csv
  resources :items, only: [ :index, :show ] do
    collection do
      match 'quick_search' => 'items#quick_search', via: [:get, :post]
      match 'search' => 'items#search', via: [:get, :post]
    end
  end
  
  resources :collections do
    collection do
      post :import
    end

    member do
      match 'search' => 'collections#search', via: [:get, :post]
    end

    resources :collection_questions, module: :collections do
      collection do
        get :preview
      end
      member do
        patch :move_up
        patch :move_down
      end
    end
    resources :collection_answers, module: :collections, only: [:edit, :update]

  end
  get "delete_image/:id", to: "collections#delete_image", as: :collection_delete_image
  get "collection/:id/items", to: "collections#items", as: :collection_items
  get 'add_item_to_checkout/:item_id', to: 'collections#add_item_to_checkout', as: :add_item_to_checkout

  get 'application/delete_attachment/:id', to: 'application#delete_attachment', as: :delete_attachment

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions"} do
    delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  
  get "home/about", to: "home#about", as: :about
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#about"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?

end

app/models/collection.rb
# == Schema Information
#
# Table name: collections
#
#  id                :bigint           not null, primary key
#  admin_group       :string
#  division          :string
#  division_page_url :string
#  link_to_policies  :string
#  short_description :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_collections_on_division  (division)
#
class Collection < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :collection_questions, dependent: :destroy
  has_many :app_preferences, dependent: :destroy
  has_rich_text :long_description
  has_one_attached :image

  validates :admin_group, presence: true, uniqueness: true
  validates :division, presence: true, uniqueness: true
  validates :division_page_url, presence: true
  validates :link_to_policies, presence: true
  validates :short_description, presence: true
  validates :long_description, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["admin_group", "created_at", "description", "division", "division_page_url", "id", "id_value", "link_to_policies", "updated_at"]
  end
end

app/controllers/collections/collection_answers_controller.rb
class Collections::CollectionAnswersController < ApplicationController
  include ActionView::Helpers::SanitizeHelper
  before_action :set_collection

  def edit
    @collection_question = CollectionQuestion.find(params[:id])
    @answer = @collection_question.collection_answers.find_by(user: current_user)
    render turbo_stream: turbo_stream.update("modal_content_frame") {
      render_to_string partial: "profiles/edit_single_collection_answer_form",
                      formats: [:html],
                      locals: { collection: @collection, collection_question: @collection_question, existing_answer: @answer }
    }
  end

  def update
    @question = CollectionQuestion.find(params[:id])

    submitted_answers = params[:collection_answers] || {}
    raw_answer = submitted_answers[@question.id.to_s]

    @answer = @question.collection_answers.find_or_initialize_by(user: current_user)

    if @question.question_type == "attachments"
      if raw_answer.present? && raw_answer.is_a?(Array)
        raw_answer.each do |uploaded_file|
          if uploaded_file.is_a?(ActionDispatch::Http::UploadedFile)
            @answer.attachments.attach(uploaded_file) # Attach the uploaded file
          end
        end
      end
    else
      answer_value = raw_answer.is_a?(Array) ? raw_answer.reject(&:blank?).join(", ") : strip_tags(raw_answer.to_s.strip)
      @answer.answer = answer_value
    end

    if @answer.save
      respond_to do |format|
        format.html { redirect_to collection_request_path, notice: "Answer updated successfully." }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_back fallback_location: collection_request_path, alert: "Failed to update answer." }
        format.turbo_stream { 
          render turbo_stream: turbo_stream.replace("flash", partial: "layouts/flash", locals: { alert: "Failed to update answer." }),
                status: :unprocessable_entity
        }
      end
    end
  end

  private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

  def collection_answer_params
    params.require(:collection_answer).permit(:answer, :collection_question_id, :user_id)
  end
end

app/controllers/collections/collection_questions_controller.rb
class Collections::CollectionQuestionsController < ApplicationController
  before_action :set_collection
  before_action :set_collection_question, only: %i[ show edit update destroy move_up move_down ]
  before_action :set_question_types, only: %i[ new edit create update ]

  def index
    @collection_questions = @collection.collection_questions.includes(:rich_text_question).order(:position)
    authorize([@collection, @collection_questions])
  end

  def show
  end
  
  def new
    @collection_question = @collection.collection_questions.build
    2.times { @collection_question.collection_options.build }
    authorize([@collection, @collection_question])
  end

  def create
    @collection_question = @collection.collection_questions.build(collection_question_params)
    authorize([@collection, @collection_question])

    respond_to do |format|
      begin
        if @collection_question.save
          if collection_question_params[:question_type].in?(%w[dropdown checkbox])
            options = params[:options_attributes].values
            options.each do |option|
              CollectionOption.create(value: option[:value], collection_question_id: @collection_question.id)
            end
          end
          format.html { redirect_to collection_collection_question_path(@collection, @collection_question), notice: "Collection question created." }
          format.json { render :show, status: :ok, location: [@collection, @collection_question] }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @collection_question.errors, status: :unprocessable_entity }
        end
      rescue => e
        @collection_question.errors.add(:base, "Unable to save: #{e.message}")
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection_question.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    2.times { @collection_question.collection_options.build } if @collection_question.collection_options.empty?
  end

  def update
    respond_to do |format|
      begin
        if @collection_question.update(collection_question_params)
          if @collection_question.question_type.in?(%w[dropdown checkbox]) && params[:options_attributes].present?
            update_options(@collection_question, params[:options_attributes].values)
          end
          format.html { redirect_to collection_collection_question_path(@collection, @collection_question), notice: "Collection question updated." }
          format.json { render :show, status: :ok, location: [@collection, @collection_question] }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @collection_question.errors, status: :unprocessable_entity }
        end
      rescue => e
        @collection_question.errors.add(:base, "Unable to save: #{e.message}")
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection_question.errors, status: :unprocessable_entity }
      end
    end
  end

  def preview
    @collection_questions = @collection.collection_questions
                                      .includes(:rich_text_question, :collection_options)
                                      .order(:position)
    authorize([@collection, @collection_questions])
  end

  def move_up
    @collection_question.move_higher
    @collection_questions = @collection.collection_questions.order(:position)
    
    respond_to do |format|
      format.turbo_stream { 
        render turbo_stream: turbo_stream.update("collection_questions_list", 
          partial: "collections/collection_questions/collection_questions_list", 
          locals: { collection_questions: @collection_questions, collection: @collection }
        )
      }
      format.html { redirect_to collection_collection_questions_path, notice: "Question moved up." }
    end
  end

  def move_down
    @collection_question.move_lower
    @collection_questions = @collection.collection_questions.order(:position)
    
    respond_to do |format|
      format.turbo_stream { 
        render turbo_stream: turbo_stream.update("collection_questions_list", 
          partial: "collections/collection_questions/collection_questions_list", 
          locals: { collection_questions: @collection_questions, collection: @collection }
        )
      }
      format.html { redirect_to collection_collection_questions_path, notice: "Question moved down." }
    end
  end
  
  def destroy
    @collection_question.destroy

    respond_to do |format|
      @collection_questions = @collection.collection_questions.order(:position)
      format.turbo_stream
      format.html { redirect_to collection_path(@collection), notice: "Collection question deleted." }
    end
  end

  private

  def update_options(question, option_params)
    question.collection_options.destroy_all
    option_params.each do |option|
      CollectionOption.create(value: option[:value], collection_question_id: question.id)
    end
  end

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

  def set_collection_question
    @collection_question = @collection.collection_questions.find(params[:id])
    authorize([@collection, @collection_question])
  end

  def set_question_types
    @question_types = CollectionQuestion.question_types.keys.map { |t| [t.humanize, t] }
  end

  def collection_question_params
    params.require(:collection_question).permit(:question, :question_type, :required, :position, :collection_id,
      collection_options_attributes: [:id, :value])
  end
    
end

app/views/collections/_collection.html.erb
<div class="shadow-sm rounded p-4">
  <div class="row g-4 align-items-center">
    <!-- Text Content -->
    <div class="col-12 col-lg-8">
      <h1 class="fw-bold mb-3"><%= collection.division %></h1>
      <% if is_super_admin? %>
        <p class="mb-2"><strong>Admin Group:</strong> <%= collection.admin_group %></p>
      <% end %>

      <p class="mb-2"><%= collection.long_description %></p>

      <p class="mb-2">
        <%= link_to "#{collection.division} Division Page", collection.division_page_url, class: "link_to" %>
      </p>

      <p class="mb-2">
        <%= link_to "#{collection.division} Policy Page", collection.link_to_policies, class: "link_to" %>
      </p>

      <% if policy(CollectionQuestion).create? %>
        <div class="mb-2">
          <%= link_to "Collection-Specific Loan Question",
                      collection_collection_questions_path(@collection),
                      class: "btn btn-primary" %>
        </div>
      <% end %>

      <div class="mb-2">
        <%= link_to "← Back to Collections", collections_path, class: "btn btn-outline-secondary" %>
      </div>
    </div>

    <!-- Right: Image -->
    <% if collection.image.attached? %>
      <div class="col-12 col-lg-4 d-flex justify-content-center">
        <div class="w-100" style="max-width: 300px;">
          <%= image_tag collection.image,
                alt: "image_#{collection.image.id}",
                class: "img-fluid img-thumbnail w-100",
                style: "height: auto;" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- Admin Actions -->
<% if policy(collection).edit? || policy(collection).destroy? %>
  <div class="mt-4 rounded p-4 shadow-sm">
    <h2 class="fw-semibold mb-3">Admin Actions</h2>

    <div class="mb-3">
      <%= render 'import' if policy(Collection).import? %>
    </div>

    <div class="d-flex flex-column flex-sm-row flex-wrap gap-2">
      <% if policy(collection).edit? %>
        <%= link_to edit_collection_path(collection), class: "btn btn-primary" do %>
          <i class="bi bi-pencil-square me-1"></i>Edit Collection
        <% end %>
      <% end %>

      <% if policy(collection).destroy? %>
        <%= button_to collection,
              method: :delete,
              class: "btn btn-danger",
              data: { turbo_confirm: "Are you sure you want to delete this collection?" } do %>
          <i class="bi bi-trash-fill me-1"></i>Delete Collection
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/collections/_collection_image.html.erb
<%= turbo_frame_tag "collection_image" do %>
  <div class="mb-3">
    <% if collection.image.attached? %>
      <div class="d-flex align-items-center gap-3">
        <span class="body-sm-text">Currently Attached:</span>        
        <%= link_to("#{h(collection.image.filename.to_s)} (#{collection.image.filename.extension})", collection.image, target: "_blank", rel: "noopener noreferrer", class: "text-decoration-none", title: "Opens image in new tab", "aria-label": "Open #{h(collection.image.filename.to_s)} image in new tab") %><br>
        <%= link_to "Delete", collection_delete_image_path(collection.id), 
            data: { 
              turbo_method: :get,
              turbo_confirm: 'Are you sure?'
            }, 
            class: "btn btn-danger btn-sm" %>
      </div>
    <% else %>
      <p class="body-sm-text">Currently Attached: None</p>
    <% end %>
  </div>
<% end %>

app/views/collections/_form.html.erb
<%= form_with(model: collection, data: { turbo: false }) do |form| %>
  <% if collection.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :division, :division.to_s.titleize %><span class="text-danger"> *</span>
    <%= form.text_field :division, required: true %>
  </div>

  <div class="mt-3">
    <%= form.label :admin_group, :admin_group.to_s.titleize %><span class="text-danger"> *</span>
    <%= form.text_field :admin_group, required: true %>
  </div>

  <div class="mt-3">
    <%= form.label :short_description, "#{:short_description.to_s.titleize} (200 characters)" %><span class="text-danger"> *</span>
    <%= form.text_area :short_description,
          class: "w-100 mt-2",
          required: true,
          maxlength: 200,
          id: "short_description_textarea" %>

    <div class="text-muted mt-1" id="char_counter">0 / 200</div>
  </div>

  <div class="mt-3">
    <%= form.label :long_description, :long_description.to_s.titleize %><span class="text-danger"> *</span>
    <%= form.rich_text_area :long_description, required: true %>
  </div>

  <div class="mt-3">
    <%= form.label :division_page_url, :division_page_url.to_s.titleize %><span class="text-danger"> *</span>
    <%= form.text_field :division_page_url, required: true %>
  </div>

  <div class="mt-3">
    <%= form.label :link_to_policies, :link_to_policies.to_s.titleize %><span class="text-danger"> *</span>
    <%= form.text_field :link_to_policies, required: true %>
  </div>

  <div class="mt-3">
    <p class="body-sm-text">
      Collection Image:
    </p>
    <div class="ms-3">
      <%= render partial: "collection_image", locals: { collection: collection } %>
    </div>
    <%= form.label :image, "Update the Image:", class: "w-100 mb-2" %>
    <%= form.file_field :image, accept: ".jpg,.jpeg,.png" %>
  </div>

  <div class="mt-3">
    <%= form.submit %>
    <% if collection.persisted? %>
      <%= link_to "Cancel", collection_path(collection), class: "link_to" %>
    <% else %>
      <%= link_to "Cancel", collections_path, class: "link_to" %>
    <% end %>
  </div>
<% end %>

<script>
  document.addEventListener("turbo:load", function () {
    const textarea = document.getElementById("short_description_textarea");
    const counter = document.getElementById("char_counter");

    if (textarea && counter) {
      function updateCounter() {
        const currentLength = textarea.value.length;
        counter.textContent = `${currentLength} / ${textarea.maxLength}`;
      }

      updateCounter();
      textarea.addEventListener("input", updateCounter);
    }
  });
</script>

app/views/collections/_import.html.erb
<div id="spinner" style="position:fixed;top:50%;left:50%;display:none;">
      <%= image_tag '12_segments.gif', alt: 'Loading' %>
    </div>
<div class="d-flex flex-column flex-sm-row flex-wrap gap-2">
  <h3 class="me-5">Import Items</h3>
  <%= form_tag import_collections_path, 
              method: :post, 
              multipart: true, 
              data: { turbo: false }, 
              onsubmit: "return showImportStart()" do %>
    <%= label_tag 'files_', 'Choose CSV files to import:', class: 'visually-hidden' %>
    <%= file_field_tag 'files[]', accept: ".csv", multiple: true %>
    <%= hidden_field_tag :collection_id, @collection.id %>
    <%= button_tag type: 'submit', class: 'btn btn-primary my-2 m-lg-0' do %>
      Import <i class="bi bi-box-arrow-in-down"></i>
    <% end %>
  <% end %>
</div>
<p>To import items into this collection, please upload two CSV files in the following order:</p>
<ul>
  <li><strong>First file:</strong> Occurrence data</li>
  <li><strong>Second file:</strong> Identification data</li>
</ul>

<script>
  function showImportStart() {
    
    const alerts = document.querySelectorAll('.alert');
    alerts.forEach(alert => {
      alert.remove();
    });

    const container = document.createElement('div');
    container.className = 'position-fixed end-0 px-3 py-6';
    container.style.top = '80px';
    container.style.zIndex = '1050';

    const alertDiv = document.createElement('div');
    alertDiv.className = 'alert alert-info alert-dismissible fade show shadow-lg';
    alertDiv.style.minWidth = '300px';
    alertDiv.setAttribute('role', 'alert');

    alertDiv.innerHTML = `
      Import initiated. Please wait without refreshing the page.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    `;
    document.getElementById('spinner').style.display = 'block';

    container.appendChild(alertDiv);
    document.body.prepend(container);
  }
</script>

app/views/collections/_item_card.html.erb
<div class="card h-100 shadow-sm" id="<%= dom_id item %>">
  <div class="card-header">
    <%= link_to item.display_name, item_path(item, return_to: request.fullpath), class: "link_to fw-bold", data: { turbo_frame: "_top" } %>
    <p class="fw-normal lh-sm"><%= item.country&.titleize %>
    <br><%= item.event_date_start %></p>
  </div>
  <div class="card-body">
    <p class="fw-normal lh-sm"><%= show_state_province_county(item) %></p>
    <p>
      <%= item.coordinates %>
    </p>
    <%= render partial: "collections/preparation_for_checkout", locals: { item: item, checkout: @checkout } %>
  </div>
</div>

app/views/collections/_preparation_for_checkout.html.erb
<div class="mt-4">
  <div class="fw-bold fs-6 mb-3">Add Preparation to Checkout</div>
  <div class="d-flex flex-wrap gap-2">

    <% item.preparations.available.each do |preparation| %>
      <% if preparation_in_checkout(preparation, @checkout) %>
        <div>
          <form action="<%= checkout_remove_preparation_path %>" method="post" data-turbo="true">
            <%= hidden_field_tag :id, preparation.id %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

            <button type="submit" class="btn btn-sm btn-success d-flex align-items-center gap-1">
              <i class="bi bi-check-circle-fill"></i>
              <%= preparation.display_name %>
            </button>
          </form>
        </div>
      <% else %>
        <div>
          <form action="<%= checkout_add_path %>" method="post" data-turbo="true">
            <%= hidden_field_tag :id, preparation.id %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

            <button type="submit" class="btn btn-sm btn-primary d-flex align-items-center gap-1">
              <i class="bi bi-square-fill"></i>
              <%= preparation.display_name %>
            </button>
          </form>
        </div>
      <% end %>
    <% end %>
  </div>
  <div>
    <% if item.preparations.unavailable.any? %>
      <div class="text-muted mb-1">Temporarily unavailable</div>
      <div class="d-flex flex-wrap gap-2">

        <% item.preparations.unavailable.each do |preparation| %>
          <div class="btn btn-sm btn-primary disabled d-flex align-items-center gap-1" style="cursor: not-allowed; opacity: 0.65;">
            <%= preparation.display_name %>
            </div>
        <% end %>
      </div>

    <% end %>

  </div>
</div>

app/views/collections/edit.html.erb
<% content_for :title, "Editing collection" %>

<h1>Editing Collection</h1>

<%= render "form", collection: @collection %>

<br>

app/views/collections/index.html.erb
<div class="">
  <% is_preview = params[:preview].present? %>
  <%= render "layouts/announcement", is_preview: is_preview, location: "collections_index" %>

  <h1 class="pt-5 text-center">Explore Collection Catalog</h1>
  <%= render "layouts/number_of_items_for_loan" %>
  <% if is_super_admin? %>
    <div class="my-3 text-end">
      <%= link_to "New Collection", new_collection_path, class: "btn btn-primary" %>
    </div>
  <% end %>
  <div class="row row-cols-1 row-cols-lg-2 g-5 mb-5">
    <% @collections.each do |collection| %>
      <div class="col">
        <%= render partial: "collection_card", locals: { collection: collection } %>
      </div>
    <% end %>
  </div>
</div>

app/views/collections/items.html.erb
<div class="container my-5">
  <h1><%= @collection.division %> items</h1>
  <%= turbo_frame_tag "all_items" do %>
    <%= form_with url: collection_items_path(@collection), method: :get, local: true, 
      data: { controller: "autosubmit",
              autosubmit_target: "form",
              turbo_frame: "all_items"
              } do %>
      <label for="per">Items per page:</label>
      <%= select_tag :per, options_for_select([15, 30, 50, 100, 150, 200], params[:per]), "data-action": "autosubmit#submit" %>
    
      <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 mb-4">
        <% @items.each do |item| %>
          <div class="col mb-5">
            <%= link_to "Add To Checkout",
                      add_item_to_checkout_path(item),
                      data: {
                        turbo_frame: "modal_content_frame",
                        bs_toggle: "modal",
                        bs_target: "#addItemToCheckoutModal"
                      },
                      class: "btn btn-sm btn-outline-primary" %>
            <%= render partial: "item_card", locals: { item: item } %>
          </div>
        <% end %>
      </div>
      <%= paginate @items %>
    <% end %>
  <% end %>
</div>

<%= render "layouts/remote_modal",
            id: "addItemToCheckoutModal",
            title: "Add Preparation to Checkout" %>

app/views/collections/new.html.erb
<% content_for :title, "New collection" %>

<h1>New Collection</h1>

<%= render "form", collection: @collection %>

<br>

app/views/collections/show.html.erb
<% content_for :head do %>
 <%= tag.meta name: "turbo-cache-control", content: "no-cache" %>
<% end %>

<div class="">
  <% if (announcement = Announcement.find_by(location: "collection_show")) && announcement.displayed? %>
    <div class="announcement">
      <%= sanitize(announcement.content.to_s) %>
    </div>
  <% end %>

  <div class="py-3">
    <%= render @collection %>
  </div>

  <div class="shadow-sm rounded p-4">
    <h4 class="fw-bold">Collection Items</h4>
    <div class="d-flex align-items-center gap-3">
      <%= search_form_for @q1, url: search_collection_path(@collection), turbo: true, data: { turbo_frame: "all_items" }, method: :post, as: :q1 do |f| %>
        <div class="rounded-3 shadow-sm search-bar-container">
          <div class="mb-2">
            <%= f.label :country_case_insensitive_or_state_province_case_insensitive_or_identifications_scientific_name_or_identifications_vernacular_name_cont,
                        "Search Items in Collection", class: "visually-hidden" %>

            <div class="input-group input-group-sm">
              <%= f.search_field :country_case_insensitive_or_state_province_case_insensitive_or_identifications_scientific_name_or_identifications_vernacular_name_cont,
                                placeholder: "Search by Scientific or Common Name or Country, State, Province",
                                class: "form-control small-search-input",
                                aria: { label: "Search" } %>

              <button class="search-icon-button" type="submit">
                <i class="bi bi-search" aria-hidden="true"></i>
                <span class="visually-hidden">Search</span>
              </button>
            </div>
          </div>
        </div>
      <% end %>
      <span class="text-black">Or go to</span>
      <%= link_to "Advanced Search", search_items_path(collection_id: @collection), class: "link_to" %>
    </div>
    <div class="mb-4">
      <%= turbo_frame_tag "all_items" do %>
        <% if @items.empty? %>
          No items available in this collection.
        <% else %>
          <%= render partial: "items" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
</div>